- name: Prompt for cluster type
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Prompt user for cluster type
    ansible.builtin.vars_prompt:
    - name: cluster_type
      prompt: "Which type of cluster do you want to create? Enter 'single' for Single Master or 'multi' for Multi-Master:"
      private: no

- name: Run setup playbook based on user choice
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Run setup playbook
    ansible.builtin.command: "ansible-playbook {{ 'setup-single.yaml' if cluster_type == 'single' else 'setup-multi.yaml' }}"


---
- hosts: all
  vars_prompt:

  - name: username
    prompt: What is your username?
    private: false

  - name: password
    prompt: What is your password?

  tasks:

  - name: Print a message
    ansible.builtin.debug:
      msg: 'Logging in as {{ username }}'
